int taco_binarySearchAfter_wrapper(int * a, int b, int c, int d) ;
int taco_binarySearchBefore_wrapper(int * a, int b, int c, int d) ;
void * calloc_wrapper(size_t a, size_t b) ;
int abs_wrapper(int a) ;
int64_t labs_wrapper(int64_t a) ;
double log10_wrapper(double a) ;
double fmod_wrapper(double a, double b) ;
float fmodf_wrapper(float a, float b) ;
double pow_wrapper(double a, double b) ;
float powf_wrapper(float a, float b) ;
double atan2_wrapper(double a, double b) ;
float atan2f_wrapper(float a, float b) ;
double fabs_wrapper(double a) ;
float fabsf_wrapper(float a) ;
double sqrt_wrapper(double a) ;
float sqrtf_wrapper(float a) ;
double exp_wrapper(double a) ;
float expf_wrapper(float a) ;
double log_wrapper(double a) ;
float logf_wrapper(float a) ;
double sin_wrapper(double a) ;
float sinf_wrapper(float a) ;
double cos_wrapper(double a) ;
float cosf_wrapper(float a) ;
double tan_wrapper(double a) ;
float tanf_wrapper(float a) ;
double asin_wrapper(double a) ;
float asinf_wrapper(float a) ;
double acos_wrapper(double a) ;
float acosf_wrapper(float a) ;
double atan_wrapper(double a) ;
float atanf_wrapper(float a) ;
double sinh_wrapper(double a) ;
float sinhf_wrapper(float a) ;
double cosh_wrapper(double a) ;
float coshf_wrapper(float a) ;
double tanh_wrapper(double a) ;
float tanhf_wrapper(float a) ;
double asinh_wrapper(double a) ;
float asinhf_wrapper(float a) ;
double acosh_wrapper(double a) ;
float acoshf_wrapper(float a) ;
double atanh_wrapper(double a) ;
float atanhf_wrapper(float a) ;

